### PR TITLE
remove kui-proxy.arch and allow ppc64le and s390x by default in requiredDuringSchedulingIgnoredDuringExecution

### PR DESCRIPTION
**Pull request by dberg1**
This is required to deploy kui-web-terminal on ppc64le.
Target is RHACM 2.3.

### CODE REVIEW

**Comment by mark-nc** [comment]
@dberg1  I was told that for RAHCM 2.3 it is only "manage to" for ppc64le (and perhaps also "manage to" Z).  Since `kui-web-terminal` is only deployed and supported on the hub cluster ("manage from") this is not a change for 2.3....or did I miss something?

**Comment by dberg1** [comment]
Hi @mark-nc. Yes, the plan is to have ppc64le support on the hub cluster ("manage from") as a Technical Preview in RHACM 2.3.

**Comment by dislbenn** [comment]
Adding the changes from [PR 56](https://github.com/open-cluster-management/kui-web-terminal-chart/pull/56) to this PR. This will just allow both features to be shipped together.

**Comment by mark-nc** [comment]
The changes in this PR were included in https://github.com/open-cluster-management/kui-web-terminal-chart/pull/56 to consolidate them with other needed chart changes. Since that PR has been merged, I am closing this PR.

**Pull request closed without merging**
